apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-portal
  labels:
    app: developer-portal
    tier: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-portal
  template:
    metadata:
      labels:
        app: developer-portal
    spec:
      containers:
      - name: portal
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: developer-portal-svc
  labels:
    app: developer-portal
spec:
  type: ClusterIP
  selector:
    app: developer-portal
  ports:
  - port: 80
    targetPort: 80
