
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-database
  namespace: enterprise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-database
  template:
    metadata:
      labels:
        app: enterprise-database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: enterprise
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-database-svc
  namespace: enterprise-backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: enterprise-database
