apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-configmap
name: prometheus-config
namespace: enterprise-control-plane
data: null
prometheus.yml: ''
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager-service:9093
rule_files:
- /etc/prometheus/alert-rules.yml
scrape_configs:
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - enterprise-backend
      - enterprise-data
      - enterprise-ingress
alert-rules.yml: ''
groups:
- name: EnterpriseSLOAlerts
  rules:
  - alert: HighErrorBudgetBurnRate
    expr: "sum(rate(http_requests_total{status=~\"5..\"}[1h])) \n/ \nsum(rate(http_requests_total[1h]))\
      \ > 0.02\n"
    for: 2m
    labels:
      severity: critical
      tier: core-business
    annotations:
      summary: High error budget burn rate detected
      description: Microservice error budget is depleting faster than 2% per hour.
        Immediate triage required.
