apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bastion
  name: bastion-deployment-deployment-1
name: enterprise-bastion-host
namespace: enterprise-security
spec:
  nodeSelector:
    topology.kubernetes.io/tier: bastion
  containers:
  - name: ssh-bastion
    image: linuxserver/openssh-server:latest
    env:
    - name: PUID
      value: '1000'
    - name: PGID
      value: '1000'
    - name: TZ
      value: UTC
    ports:
    - containerPort: 22
      name: ssh
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 64Mi
replicas: 1
selector: null
matchLabels:
  app: bastion
template: null
---
apiVersion: v1
kind: Service
metadata:
  name: bastion-deployment-service-2
name: ssh
namespace: enterprise-security
spec: null
type: LoadBalancer
selector: null
app: bastion
ports:
- port: 22
targetPort: 22
