apiVersion: v1
kind: Namespace
metadata:
  name: falco-security-namespace-1
name: enterprise-security
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: falco
  name: falco-security-daemonset-2
name: falco-runtime-security
namespace: enterprise-security
spec:
  nodeSelector:
    topology.kubernetes.io/tier: security
  hostNetwork: true
  hostIPC: true
  hostPID: true
  containers:
  - name: falco
    image: falcosecurity/falco:latest
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
selector: null
matchLabels:
  app: falco
template: null
