apiVersion: v1
kind: Namespace
metadata:
  name: falco-security-namespace-1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-runtime-security
  namespace: falco-security-namespace-1
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      hostNetwork: true
      hostIPC: true
      hostPID: true
      containers:
      - name: falco
        image: falcosecurity/falco:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
