apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-iot-broker
  namespace: enterprise-iot
  labels:
    app: mqtt-broker
    tier: tier9-edge-iot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.3.0
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 18083
          name: dashboard
        env:
        - name: EMQX_ALLOW_ANONYMOUS
          value: 'true'
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 15
          periodSeconds: 10
