apiVersion: v1
kind: Service
metadata:
name: iot-broker-service
namespace: enterprise-iot
spec:
selector:
app: mqtt-broker
ports:
- port: 1883
targetPort: 1883
name: mqtt
- port: 9001
targetPort: 9001
name: websockets
type: ClusterIP
