apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enterprise-database
  labels:
    app: enterprise-database
spec:
  serviceName: "enterprise-database"
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-database
  template:
    metadata:
      labels:
        app: enterprise-database
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "secretpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-database-svc
  labels:
    app: enterprise-database
spec:
  clusterIP: None
  selector:
    app: enterprise-database
  ports:
  - port: 5432
    targetPort: 5432
