apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterprise-database-netpol
  namespace: enterprise-data
spec:
  podSelector:
    matchLabels:
      app: enterprise-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: enterprise-backend
    ports:
    - protocol: TCP
      port: 5432
