apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: velero-backup
  name: velero-backup-deployment
name: velero-backup-agent
namespace: enterprise-control-plane
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/tier
            operator: In
            values:
            - backup
  containers:
  - name: velero
    image: velero/velero:v1.12.0
    command:
    - /velero
    - server
    resources:
      requests:
        cpu: 500m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 64Mi
replicas: 1
selector: null
matchLabels:
  app: velero-backup
template: null
