apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: enterprise.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-backend-svc
            port:
              number: 8080
