apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-validator-deployment
  namespace: gatekeeper-system
  labels:
    app: opa-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-validator
  template:
    metadata:
      labels:
        app: opa-validator
    spec:
      containers:
      - name: validator
        image: openpolicyagent/gatekeeper:latest
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: opa-validator-svc
  namespace: gatekeeper-system
spec:
  type: ClusterIP
  selector:
    app: opa-validator
  ports:
  - port: 443
    targetPort: 8443
