apiVersion: apps/v1
kind: Deployment
metadata:
  serverAddress: http://prometheus-service.enterprise-control-plane.svc.cluster.local:9090
  metricName: http_requests_total
  query: sum(rate(http_requests_total{namespace="enterprise-backend"}[2m]))
  threshold: '100'
  name: keda-backend-scaler-deployment
name: core-business-api
namespace: enterprise-backend
spec: null
scaleTargetRef: null
minReplicaCount: 2
maxReplicaCount: 20
cooldownPeriod: 300
pollingInterval: 15
triggers:
- type: prometheus
